name: Dev-Deployment Pratham-OU Mumbai Region
on:
  push:
    branches:
      - east-africa-ym
jobs:
  DEV-DEPLOYMENT:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Extract Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Deploy Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          key: ${{ secrets.EC2_SSH_KEY_DEV }}
          port: ${{ secrets.PORT_DEV }}
          script: |
            cd ${{ secrets.TARGET_DIR_DEV }}
            if [ -f .env ]; then
              rm .env
            fi
            echo '${{ secrets.DEV_ENV }}"' > .env
            ls -ltra
            ./deploy.sh ${{ env.BRANCH_NAME }}
